services:
  traefik:
    image: traefik:v3.3
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  api:
    build:
      context: ../src/api
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - nats
      - traefik
    environment:
      - NATS_URL=${NATS_URL}
      - API_URL=${API_URL}
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=(Host(`lead-locate.netlify.app`) && PathPrefix(`/api`))"
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
      - "traefik.http.routers.api.middlewares=api-strip@docker"
      - "traefik.http.services.api.loadbalancer.server.port=8888"
      - "traefik.http.routers.api.priority=100"

  frontend:
    build:
      context: ../src/frontend/GMAPS
      dockerfile: Dockerfile
    ports:
      - "8008:80"
    depends_on:
      - api
      - traefik
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`lead-locate.netlify.app`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend.priority=10"
  gowler:
    build:
      context: ../src/gowler
      dockerfile: Dockerfile
    depends_on:
      - nats
    environment:
      - NATS_URL=${NATS_URL}
      - MAPS_API_KEY=${MAPS_API_KEY}
    env_file:
      - ./.env
  nats:
    image: nats:2.10.26-alpine3.21
    ports:
      - "4222:4222"
  
  postgres:
    build:
      context: ../src/postgres
      dockerfile: Dockerfile
    container_name: lead_locate_postgres
    ports:
      - 5432:5432
    volumes:
      - ../src/postgres/data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=lead_locate
    env_file:
      - ./.env

